# Generated by Django 3.2.7 on 2021-12-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211230_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date',
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.FloatField(max_length=10),
        ),
    ]
