# Generated by Django 3.2.7 on 2022-01-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20211230_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.FloatField(max_length=10),
        ),
    ]
