# Generated by Django 3.2.7 on 2022-01-02 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20220102_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='imageFile',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 11, 29, 33, 237055, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 2, 11, 29, 33, 236056, tzinfo=utc)),
        ),
    ]
