# Generated by Django 3.2.7 on 2022-01-16 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auto_20220116_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='watchers',
            new_name='watcher',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 10, 35, 18, 87145, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 10, 35, 18, 87145, tzinfo=utc)),
        ),
    ]
